### ISSUE TITLE
Doesn't work for Visual Studio 17.4.0 and 17.5 Preview

### ISSUE THREAD

**Issue by AlexanderEgurtsovDX** [microsoft/vs-extension-testing#133]
It seems that the testing is broken for just released  VS 17.4.

From a short debug, something is going wrong inside https://github.com/microsoft/vs-extension-testing/blob/0158b24d486399ca1d49f5ab2072a09143783cd1/src/Microsoft.VisualStudio.VsixInstaller.Shared/Installer.cs#L102
VsixInstaller is just hanged here.

During debug I can see the following exception:
System.Runtime.InteropServices.COMException: 'Element not found. (Exception from HRESULT: 0x80070490)'
in https://github.com/microsoft/vs-extension-testing/blob/0158b24d486399ca1d49f5ab2072a09143783cd1/src/Microsoft.VisualStudio.VsixInstaller.Shared/Installer.cs#L96

Also, during assembly resolving inside the  HandleAssemblyResolve method it's failed to find the
***Microsoft.VisualStudio.ExtensionEngine.XmlSerializers, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a***
assembly.

I can reproduce the VsixInstaller.17 hang when running the TestOpenAndCloseIDE test inside IntegrationTests. 

Things was working well for 17.3 and for at least some versions of 17.4 Preview(didn't run integrations tests for a latest Preview update).

**Comment by sharwell** [comment]
I was expecting this to be fixed by #129. Can you make sure you are using 0.1.145-beta or newer?

**Comment by AlexanderEgurtsovDX** [comment]
@sharwell ,

Thank you for the update. Actually, I was testing using the latest sources - but something seems to be broken on my machine during tests. Today I double-checked, and tests was working for code in this repository and in our internal fork.

Thank you for your assistance!
